services:
  frontend:
    container_name: pass-mais
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3333
    networks:
      - passmais-network

networks:
  passmais-network:
    driver: bridge
