services:
  pass-mais:
    container_name: pass-mais
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3333
    networks:
      - passmais-networkk

networks:
  passmais-network:
    external: true
