name: Deploy to ECS Fargate

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag e push da imagem
      run: |
        cd pass-mais
        docker build -t pass-mais:latest .
        docker tag pass-mais:latest ${{ secrets.ECR_REPOSITORY_URI }}/${{ secrets.ECR_REPOSITORY }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_URI }}/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Forçar redeploy no ECS com imagem :latest
      run: |
        aws ecs update-service \
          --cluster meu-cluster \
          --service meu-app-service \
          --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
