name: CI/CD – Deploy em EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Deploy via SSH na EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/PassMais-frontend/pass-mais
          git pull
          sudo docker compose up --build -d

    - name: Marcar deploy OK no GitHub
      run: echo "🚀 Deploy finalizado com sucesso!!"
